{
 "title": "DC Overview Copy",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  {
   "title": "Topology",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 23, "w": 16, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "interface_oper_state",
     "legendFormat": "{{source}}-{{interface_name}}-operstate"
    },
    {
     "expr": "interfaces_interface_state_oper_status",
     "legendFormat": "{{source}}-{{interface_name}}-operstate"
    },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}-{{interface_name}}-traffic_rate-out"
    },
    {
     "expr": "rate(interfaces_interface_state_counters_out_octets[$__rate_interval]) * 8",
     "legendFormat": "{{source}}-{{interface_name}}-traffic-out"
    },
    {
     "expr": "interface_traffic_rate_in_bps",
     "legendFormat": "{{source}}-{{interface_name}}-traffic_rate_in"
    },
    {
     "expr": "openconfig_interfaces_interfaces_interface_state_admin_status",
     "legendFormat": "{{source}}-{{interface_name}}"
    }
   ]
  },
  {
   "title": "Total Traffic Rack-1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(interface_traffic_rate_in_bps)",
     "legendFormat": "Ingress Traffic"
    },
    {
     "expr": "sum(interface_traffic_rate_out_bps)",
     "legendFormat": "Egress Traffic"
    }
   ]
  },
  {
   "title": "Total Traffic Rack-2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(interfaces_interface_state_counters_in_octets[1m])) * 8",
     "legendFormat": "Ingress Traffic"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_out_octets[1m])) * 8",
     "legendFormat": "Egress Traffic"
    }
   ]
  },
  {
   "title": "Top Talkers Rack1",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(interface_name) (1, interface_traffic_rate_in_bps)",
     "legendFormat": "{{source}}-{{interface_name}}"
    }
   ]
  },
  {
   "title": "BGP Peers",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_peers",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "Node" },
  {
   "title": "Port Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_oper_state{source=\"$Node\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Utilization Ingress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"$Node\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Utilization Egress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps{source=\"$Node\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Packets Counts",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_statistics_in_unicast_packets{source=\"$Node\"}",
     "legendFormat": "Unicast-{{interface_name}}"
    },
    {
     "expr": "interface_statistics_in_broadcast_packets{source=\"$Node\"}",
     "legendFormat": "Broadcast-{{interface_name}}"
    },
    {
     "expr": "interface_statistics_in_multicast_packets{source=\"$Node\"}",
     "legendFormat": "Multicast-{{interface_name}}"
    }
   ]
  },
  {
   "title": "BGP Peers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_peers{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Routes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_received_routes{source=\"$Node\"}",
     "legendFormat": "received-routes"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_active_routes{source=\"$Node\"}",
     "legendFormat": "active-routes"
    },
    { "expr": "sent", "legendFormat": "__auto" }
   ]
  }
 ]
}