{
 "title": "Datacenter Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "label": "Rack1 Nodes", "query": { "query": "label_values(source)" } },
   { "name": "Node2", "label": "Rack2 Nodes", "query": { "query": "label_values(source)" } },
   { "name": "Node3", "label": "Rack3 Nodes", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Traffic Rack-1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(interface_traffic_rate_in_bps)",
     "legendFormat": "Ingress Traffic"
    },
    {
     "expr": "sum(interface_traffic_rate_out_bps)",
     "legendFormat": "Egress Traffic"
    }
   ]
  },
  {
   "title": "Total Traffic Rack-2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(interfaces_interface_state_counters_in_octets[1m])) * 8",
     "legendFormat": "Ingress Traffic"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_out_octets[1m])) * 8",
     "legendFormat": "Egress Traffic"
    }
   ]
  },
  {
   "title": "Topology",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "interface_oper_state",
     "legendFormat": "{{source}}-{{interface_name}}-operstate"
    },
    {
     "expr": "interfaces_interface_state_oper_status",
     "legendFormat": "{{source}}-{{interface_name}}-operstate"
    },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}-{{interface_name}}-traffic_rate-out"
    },
    {
     "expr": "rate(interfaces_interface_state_counters_out_octets[$__rate_interval]) * 8",
     "legendFormat": "{{source}}-{{interface_name}}-traffic-out"
    },
    {
     "expr": "interface_traffic_rate_in_bps",
     "legendFormat": "{{source}}-{{interface_name}}-traffic_rate_in"
    },
    {
     "expr": "openconfig_interfaces_interfaces_interface_state_admin_status",
     "legendFormat": "{{source}}-{{interface_name}}"
    }
   ]
  },
  {
   "title": "BGP Peers",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_peers",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Top Talkers Rack1",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(interface_name) (1, interface_traffic_rate_in_bps)",
     "legendFormat": "{{source}}-{{interface_name}}"
    }
   ]
  },
  {
   "title": "Rack1 Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "Node",
   "collapsed": true,
   "panels": [
    {
     "title": "Port Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "interface_oper_state{source=\"$Node\"}",
       "legendFormat": "{{interface_name}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "platform_control_cpu_total_instant{source=\"$Node\"}",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 28 },
     "targets": [
      {
       "expr": "platform_control_cpu_total_instant{source=\"$Node\"}",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "platform_control_memory_free{source=\"$Node\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "platform_control_memory_utilization{source=\"$Node\"}",
       "legendFormat": "Utilization"
      },
      {
       "expr": "platform_control_memory_physical{source=\"$Node\"}",
       "legendFormat": "Physical"
      }
     ]
    },
    {
     "title": "Utilization Ingress",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "interface_traffic_rate_in_bps{source=\"$Node\"}",
       "legendFormat": "{{interface_name}}"
      }
     ]
    },
    {
     "title": "Utilization Egress",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "interface_traffic_rate_out_bps{source=\"$Node\"}",
       "legendFormat": "{{interface_name}}"
      }
     ]
    },
    {
     "title": "Packets Counts",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "interface_statistics_in_unicast_packets{source=\"$Node\"}",
       "legendFormat": "Unicast-{{interface_name}}"
      },
      {
       "expr": "interface_statistics_in_broadcast_packets{source=\"$Node\"}",
       "legendFormat": "Broadcast-{{interface_name}}"
      },
      {
       "expr": "interface_statistics_in_multicast_packets{source=\"$Node\"}",
       "legendFormat": "Multicast-{{interface_name}}"
      }
     ]
    },
    {
     "title": "BGP Peers",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "network_instance_protocols_bgp_statistics_total_peers{source=\"$Node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BGP Routes",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "network_instance_protocols_bgp_statistics_total_active_routes{source=\"$Node\"}",
       "legendFormat": "Active Routes"
      },
      {
       "expr": "network_instance_protocols_bgp_statistics_total_received_routes{source=\"$Node\"}",
       "legendFormat": "Received Routes"
      },
      {
       "expr": "network_instance_protocols_bgp_statistics_total_prefixes{source=\"$Node\"}",
       "legendFormat": "Total Underlay Prefixes"
      }
     ]
    },
    {
     "title": "BGP Routes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "network_instance_protocols_bgp_statistics_total_received_routes{source=\"$Node\"}",
       "legendFormat": "received-routes"
      },
      {
       "expr": "network_instance_protocols_bgp_statistics_total_active_routes{source=\"$Node\"}",
       "legendFormat": "active-routes"
      },
      { "expr": "sent", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Rack2 Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "Node2" },
  {
   "title": "Enabled Interfaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interfaces_interface_state_oper_status{source=\"$Node2\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Bandwidth Utilization Egress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(interfaces_interface_state_counters_out_octets{source=\"$Node2\"}[$__rate_interval]) * 8",
     "legendFormat": "{{source}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Bandwidth Utilization Ingress",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(interfaces_interface_state_counters_in_octets{source=\"$Node2\"}[$__rate_interval]) * 8",
     "legendFormat": "{{source}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Overlay EVPN Routes - Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_prefixes_sent{source=\"$Node2\", afi_safi_afi_safi_name=\"L2VPN_EVPN\", neighbor_neighbor_address=\"11.11.11.11\"}",
     "legendFormat": "Sent"
    },
    {
     "expr": "network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_prefixes_installed{source=\"$Node2\", afi_safi_afi_safi_name=\"L2VPN_EVPN\", neighbor_neighbor_address=\"11.11.11.11\"}",
     "legendFormat": "Installed "
    },
    {
     "expr": "network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_prefixes_received{source=\"$Node2\", afi_safi_afi_safi_name=\"L2VPN_EVPN\", neighbor_neighbor_address=\"11.11.11.11\"}",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "BGP Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state{source=\"$Node2\"}",
     "legendFormat": "{{neighbor_neighbor_address}}"
    }
   ]
  },
  { "title": "Rack3 Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "repeat": "Node3" },
  {
   "title": "Enabled Interfaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openconfig_interfaces_interfaces_interface_state_admin_status{source=\"$Node3\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  }
 ]
}