# Copyright 2025 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
timeout: 10s

common_srl_subscriptions: &common_srl_subs
  port: 57400
  skip-verify: true
  insecure: false
  password: NokiaSrl1!
  subscriptions:
    - srl-if-stats
    - srl-bgp
    - srl-system-performance
    - srl-routes
    - srl-bridge
    - srl-apps
    - srl-net-instance
    
targets:
  #SRLinux
  leaf1: *common_srl_subs
  leaf2: *common_srl_subs
  spine1: *common_srl_subs
  spine2: *common_srl_subs

  #Arista
  leaf3:6030:
    username: admin
    password: admin
    # port: 6030
    skip-verify: true
    insecure: true
    subscriptions:
      - arista-if-stats
    
  leaf4:6030:
    username: admin
    password: admin
    # port: 6030
    skip-verify: true
    insecure: true
    subscriptions:
      - arista-if-stats

  leaf5:8080:
    username: admin
    password: admin
    insecure: true
    subscriptions:
      - sonic-if-stats
    
subscriptions:
  srl-system-performance:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /platform/control[slot=*]/cpu[index=all]/total
      - /platform/control[slot=*]/memory
  srl-if-stats:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=ethernet-1/*]/oper-state
      - /interface[name=ethernet-1/*]/statistics
      - /interface[name=ethernet-1/*]/traffic-rate
  srl-routes:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /network-instance[name=*]/route-table/ipv4-unicast/statistics/
      - /network-instance[name=*]/route-table/ipv6-unicast/statistics/
  srl-bgp:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /network-instance[name=*]/protocols/bgp/statistics
  srl-bridge:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /network-instance[name=*]/bridge-table/statistics/
  srl-apps:
    paths:
      - /system/app-management/application[name=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s
  srl-net-instance:
    paths:
      - /network-instance[name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  arista-if-stats:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interfaces/interface[name=Ethernet1]/state/oper-status
      - /interfaces/interface[name=Ethernet2]/state/oper-status
      - /interfaces/interface[name=Ethernet3]/state/oper-status
      - /interfaces/interface[name=Ethernet4]/state/oper-status
      - /interfaces/interface[name=Ethernet5]/state/oper-status
      - /interfaces/interface[name=Ethernet10]/state/oper-status
      - /interfaces/interface/state/counters
      - /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state
      - /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor

  sonic-if-stats:
    mode: stream
    target: OC-YANG
    stream-mode: sample
    sample-interval: 20s
    paths:
      - /interfaces/interface[name=Ethernet0]/state/admin-status
      - /interfaces/interface[name=Ethernet4]/state/admin-status
      - /interfaces/interface[name=Ethernet36]/state/admin-status

  sonic_counters_port:
    paths:
      - "COUNTERS/Ethernet0"
      - "COUNTERS/Ethernet4"
      - "COUNTERS/Ethernet36"
    target: COUNTERS_DB
    stream-mode: stream
    sample-interval: 20s

outputs:
  prom-output:
    type: prometheus
    listen: :9273
    event-processors:
      # - trim-prefixes
      # - rename-srl-interface
      - oper-state-to-int

processors:
  # trim-prefixes:
  #   event-strings:
  #     value-names:
  #       - "^/state/.*"
  #     transforms:
  #       - trim-prefix:
  #           apply-on: "name"
  #           prefix: "/state/"

  oper-state-to-int:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "UP"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
        - replace:
            apply-on: "value"
            old: "DOWN"
            new: "0"
        - replace:
            apply-on: "value"
            old: "ESTABLISHED"
            new: "1"
        - replace:
            apply-on: "value"
            old: "IDLE"
            new: "0"
        - replace:
            apply-on: "value"
            old: "ACTIVE"
            new: "0"
        - replace:
            apply-on: "value"
            old: "CONNECT"
            new: "0"
  # rename-srl-interface:
  #   event-strings:
  #     tag-names:
  #       - "^interface_name"
  #     transforms:
  #       - replace:
  #           apply-on: "value"
  #           old: "ethernet-(\\d+)/(\\d+)"
  #           new: "e$1-$2"

